<br /><br />
<?php printf(CMA_Settings::__('This plugin was developed by %s'), '<a href="http://cminds.com/" target="new">CreativeMinds</a>'); ?>.
<?php printf(CMA_Settings::__('You can find more information about CM Answers on website: %s'), '<a href="http://answers.cminds.com" target="new">answers.cminds.com</a>'); ?>

<br /><br />
<h3><strong>Video Demo</strong></h3>
<iframe width="560" height="315" src="//www.youtube.com/embed/px1IOEKOcr4" frameborder="0" allowfullscreen></iframe>

<br /><br />
<h3><?php echo CMA_Settings::__('Premium Plugins by CreativeMinds'); ?></h3>
<div><iframe src="<?php echo esc_attr($iframeURL) ?>" height="700" style="width: 100%" ></iframe></div>

<br />
<h3><?php echo CMA_Settings::__('We Are Experts in Custom Plugin Development'); ?></h3>
<ul>
    <li><strong><?php echo CMA_Settings::__('Professional Quality Work'); ?></strong> - <?php echo CMA_Settings::__('We follow a detailed coding standard that ensures we deliver only the highest quality products and services. You can count on maintainable code that fulfills your requirements completely.'); ?></li>
    <li><strong><?php echo CMA_Settings::__('Expert Knowledge'); ?></strong> - <?php echo CMA_Settings::__('Custom WordPress plugins are our specialty. We devote a lot of work and time for testing to deliver to our customers bug free products. We use WP custom functions and we excel in PHP / SQL / JavaScript and related technologies like JQuery or Ajax.'); ?></li>
    <li><strong><?php echo CMA_Settings::__('Integration with 3rd-party Plugins'); ?></strong> - <?php echo CMA_Settings::__('Upon request we integrate our plugins with external 3-rd party tools and services such as GoToMeeting, Vimeo, Google and many others.'); ?></li>
    <li><strong><?php echo CMA_Settings::__('Fixed Price Quotes'); ?></strong> - <?php echo CMA_Settings::__('We provide fixed price quotes so you know exactly what your total and final development cost will be.'); ?></li>
    <li><strong><?php echo CMA_Settings::__('Support and Warranty'); ?></strong> - <?php echo CMA_Settings::__('Once your plugin is completed we will not leave you out in the cold. We believe that your success is our success and we want happy customers who will use our products again.'); ?></li>
</ul>