<br /><br />
<?php printf(CMA_Settings::__('This plugin was developed by %s'), '<a href="http://cminds.com/" target="new">CreativeMinds</a>'); ?>.
<?php printf(CMA_Settings::__('You can find more information about CM Answers on website: %s'), '<a href="http://answers.cminds.com" target="new">answers.cminds.com</a>'); ?>
<br /><br />

<div><iframe src="https://www.cminds.com/store/?showfilter=No&amp;tags=Answer&amp;nitems=2" height="700" style="width: 100%"></iframe></div>