<div class="cma-rating">
	<a class="cma-thumbs-up" title="<?php echo esc_attr(CMA::__('Thumbs Up!')); ?>">&#9650;</a>
	<div class="cma-rating-count"><?php echo $rating; ?></div>
	<a class="cma-thumbs-down" title="<?php echo esc_attr(CMA::__('Thumbs Down!')); ?>">&#9660;</a>
</div>

<div class="cma-best-answer-icon" title="<?php echo esc_attr($bestAnswerLabel); ?>"><span class="icon">&#10004;</span></div>